<a href="https://colab.research.google.com/github/rohinikshirasagar123-crypto/Import-_numpy-/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("1D Array:", a)
print("Shape:", a.shape)
print("Dtype:", a.dtype)

print("\n2D Array:")
print(b)
print("Shape:", b.shape)
print("Dtype:", b.dtype)

1D Array: [10 20 30 40 50]
Shape: (5,)
Dtype: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dtype: int64


In [ ]:
import numpy as np

a = np.zeros(8)
b = np.ones((4,4))
c = np.zeros((3,3))

print("1D Zeros")
print(a)

print("\n4x4 Ones")
print(b)

print("\n3x3 Zeros")
print(c)

1D Zeros
[0. 0. 0. 0. 0. 0. 0. 0.]

4x4 Ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

print(np.arange(0,21))
print()

print(np.arange(10,51,2))
print()

print(np.arange(5,101,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
import numpy as np

a = np.linspace(0,5,10)
b = np.linspace(-10,10,15)

print(a)
print("Length:",len(a))

print()

print(b)
print("Length:",len(b))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [ ]:
import numpy as np

a = np.random.rand(10)
b = np.random.randn(3,3)
c = np.random.randint(10,51,(4,5))

print("Random Numbers")
print(a)

print("\nNormal Distribution")
print(b)

print("\nRandom Integers")
print(c)

Random Numbers
[0.49501518 0.18276308 0.51706278 0.22648558 0.23248416 0.01256532
 0.34803292 0.36809869 0.27353384 0.42858283]

Normal Distribution
[[ 0.28374486 -0.7018361   0.67240312]
 [-0.74198951 -0.35670007 -0.37580775]
 [ 0.47041568 -1.73700611  2.46407021]]

Random Integers
[[32 18 12 20 14]
 [31 48 18 49 46]
 [30 42 39 46 37]
 [26 25 43 49 15]]


In [ ]:
import numpy as np

v1=np.array([2,4,6,8])
v2=np.array([1,3,5,7])

print("Addition:",v1+v2)
print("Subtraction:",v1-v2)
print("Multiplication:",v1*v2)
print("Dot Product:",np.dot(v1,v2))

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Multiplication: [ 2 12 30 56]
Dot Product: 100


In [ ]:
import numpy as np

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Addition")
print(A+B)

print("\nMatrix Multiplication")
print(A@B)

print("\nElement-wise Multiplication")
print(A*B)

Addition
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
import numpy as np

A=np.random.randint(1,101,(4,4))

print(A)

print("Shape:",A.shape)
print("Dimension:",A.ndim)
print("Size:",A.size)
print("Data Type:",A.dtype)
print("Minimum:",A.min())
print("Maximum:",A.max())

[[23 54 10 96]
 [ 9 91 27 89]
 [97 65 40 83]
 [85 85 99 71]]
Shape: (4, 4)
Dimension: 2
Size: 16
Data Type: int64
Minimum: 9
Maximum: 99


In [ ]:
import numpy as np

A=np.random.randint(1,51,20)
B=A.reshape(4,5)

print(B)

print("Sum:",B.sum())
print("Mean:",B.mean())
print("Standard Deviation:",B.std())

print("Maximum in each row:")
print(B.max(axis=1))

[[22  5 16  9  4]
 [ 9 10 50 17 15]
 [38 49 22  1 34]
 [31  2  6 44 39]]
Sum: 423
Mean: 21.15
Standard Deviation: 15.89740544868879
Maximum in each row:
[22 50 49 44]


In [ ]:
import numpy as np

try:
    n=int(input("How many numbers: "))

    arr=np.random.randint(10,101,n)

    print("\nArray:")
    print(arr)

    print("Mean:",np.mean(arr))
    print("Median:",np.median(arr))
    print("Standard Deviation:",np.std(arr))
    print("Minimum:",np.min(arr))
    print("Maximum:",np.max(arr))

    if n%2==0:
        a=arr.reshape(2,n//2)
        print("\n2D Array")
        print(a)

        print("Row-wise Sum")
        print(a.sum(axis=1))
    else:
        print("\nCannot reshape into 2D array.")

except:
    print("Invalid Input")

How many numbers: 50

Array:
[36 24 62 69 10 68 82 99 16 86 11 27 33 63 81 93 79 87 45 11 49 89 83 76
 66 17 43 45 29 15 27 57 74 84 48 78 50 92 14 81 54 57 38 49 92 98 22 79
 44 61]
Mean: 55.86
Median: 57.0
Standard Deviation: 26.864854364019916
Minimum: 10
Maximum: 99

2D Array
[[36 24 62 69 10 68 82 99 16 86 11 27 33 63 81 93 79 87 45 11 49 89 83 76
  66]
 [17 43 45 29 15 27 57 74 84 48 78 50 92 14 81 54 57 38 49 92 98 22 79 44
  61]]
Row-wise Sum
[1445 1348]
